services:
  - type: web
    name: reportes-siga-updater
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      gunicorn --bind 0.0.0.0:$PORT api.app:app
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SIGA_USERNAME
        value: api_user
      - key: SIGA_PASSWORD
        value: Api_user123*